### ISSUE TITLE
Setup wasm couldn't install emcc

### ISSUE THREAD

**Issue by vinc** [lord/wargo#14]
I'm using Arch Linux so I had to change `python` to `python2` in `setup.js`, but then I get that error:

```
$ wargo build                                      
  Setup wasm checking dependencies...
  Setup wasm emsdk not found, installing to ~/.emsdk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36333  100 36333    0     0  36333      0  0:00:01 --:--:--  0:00:01 41570
emsdk-portable/emsdk
emsdk-portable/emcmdprompt.bat
emsdk-portable/emsdk.bat
emsdk-portable/emsdk_manifest.json
emsdk-portable/emsdk_env.bat
emsdk-portable/README.md
emsdk-portable/binaryen-tags.txt
emsdk-portable/emscripten-tags.txt
emsdk-portable/emsdk_env.sh
  Setup wasm setting environment...
  Setup wasm installing emcc...
Fetching all tags from Emscripten Github repository...
Done. 109 tagged releases available, latest is 1.37.22.
Fetching all tags from Binaryen Github repository...
Done. 36 tagged Binaryen releases available, latest is 1.37.22.
Fetching all precompiled Nightly versions..
Downloading: /home/v/.emsdk/llvm-nightlies-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/linux_32bit/index.txt
Downloading: /home/v/.emsdk/llvm-nightlies-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/nightly/linux_64bit/index.txt, 21647 Bytes                                                                                                                                          Downloading: /home/v/.emsdk/emscripten-nightlies.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/emscripten/nightly/linux/index.txt, 22480 Bytes                                                                                                                                          Fetching all precompiled tagged releases..
Downloading: /home/v/.emsdk/llvm-tags-32bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_32bit/index.txt
Downloading: /home/v/.emsdk/llvm-tags-64bit.txt from https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_64bit/index.txt, 789 Bytes                                                                                                                                                     Installing SDK 'sdk-1.37.22-64bit'..
Done installing SDK 'sdk-1.37.22-64bit'.
Writing .emscripten configuration file to user home directory /home/v/
The Emscripten configuration file /home/v/.emscripten has been rewritten with the following contents:

import os
SPIDERMONKEY_ENGINE = ''
NODE_JS = 'node'
V8_ENGINE = ''
TEMP_DIR = '/tmp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]

To conveniently access the selected set of tools from the command line, consider adding the following directories to PATH, or call 'source ./emsdk_env.sh' to do this for you.

   /home/v/.emsdk
  Setup wasm couldn't install emcc. file a bug at https://github.com/lord/wargo?
/bin/sh: emcc: command not found
child_process.js:634
    throw err;
    ^

Error: Command failed: emcc -v
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at module.exports (/usr/lib/node_modules/wargo/src/cmd.js:30:16)
    at getos (/usr/lib/node_modules/wargo/index.js:19:26)
    at /usr/lib/node_modules/wargo/node_modules/getos/index.js:95:16
    at /usr/lib/node_modules/wargo/node_modules/async/dist/async.js:460:16
    at iteratorCallback (/usr/lib/node_modules/wargo/node_modules/async/dist/async.js:1034:13)
    at /usr/lib/node_modules/wargo/node_modules/async/dist/async.js:944:16
    at /usr/lib/node_modules/wargo/node_modules/getos/index.js:87:20
    at customLogic (/usr/lib/node_modules/wargo/node_modules/getos/index.js:123:72)
```

**Comment by lord** [comment]
Did you change where `python` pointed to, or did you just modify the check in `setup.js`? If you just modified the check, it would fail because `emsdk` expects Python 2.

**Comment by vinc** [comment]
Ah, thanks! Indeed I just edited `setup.js` to point to `python2`, so I did the same in `emsdk` and now the setup is working! We can probably close this issue because it's related to #9.

The build then fail to compile one of the dependencies of my project but that's another thing ^^

**Comment by lord** [comment]
Yea, once you're compiling a hello world example, you're probably on your own re: compiling dependencies. I'll close this but keep #9 open as a reminder to fix the python issue. Glad it's working now!
