### ISSUE TITLE
No unique release file

### ISSUE THREAD

**Issue by flosse** [lord/wargo#6]
Running `wargo build` causes a `Error: No unique release file found!` :(
What exactly does this mean?

**Comment by lord** [comment]
What OS/version are you on?

**Comment by lord** [comment]
And if you could post the full output of running `wargo build`, that would be great!

**Comment by flosse** [comment]
> What OS/version are you on?

NixOS

> And if you could post the full output of running `wargo build`, that would be great!

```
./node_modules/.bin/wargo build
Error: No unique release file found!
    at /home/mk/dev/hello-wargo/node_modules/getos/index.js:147:21
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by lord** [comment]
Thanks for the details! Does the fix in the `fix6` branch fix it for you? You can test it out with

    git clone https://github.com/lord/wargo.git
    cd wargo
    git checkout fix6
    npm install -g
    wargo setup

**Comment by flosse** [comment]
Now it works a bit ...
```
./node_modules/.bin/wargo setup
  Setup wasm warning: os identification error:  Error: No unique release file found!
    at /home/mk/dev/hello-wargo/node_modules/getos/index.js:147:21
    at FSReqWrap.oncomplete (fs.js:123:15)
  Setup wasm using emcc already in $PATH
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.16clang version 4.0.0  (emscripten 1.37.16 : 1.37.16)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/3p7297ns35i880cmswvdyixw10nw0zaf-emscripten-fastcomp-1.37.16/bin
Found candidate GCC installation: /nix/store/g65l985579ri87i8m3906a2nmyrl24a2-gcc-6.4.0/lib/gcc/x86_64-unknown-linux-gnu/6.4.0
Found candidate GCC installation: /nix/store/g65l985579ri87i8m3906a2nmyrl24a2-gcc-6.4.0/lib64/gcc/x86_64-unknown-linux-gnu/6.4.0
Selected GCC installation: /nix/store/g65l985579ri87i8m3906a2nmyrl24a2-gcc-6.4.0/lib64/gcc/x86_64-unknown-linux-gnu/6.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```
...but building fails because I did not install the `std` for `wasm32-unknown-emscripten` ;-)

```
  Setup wasm running 'cargo build --target=wasm32-unknown-emscripten'
   Compiling meow v0.1.0 (file:///home/mk/dev/hello-wargo/meow)
error[E0463]: can't find crate for `std`
  |
  = note: the `wasm32-unknown-emscripten` target may not be installed

error: aborting due to previous error

error: Could not compile `meow`.

To learn more, run the command again with --verbose.
```

**Comment by lord** [comment]
Hrm, that's really weird. The checks should automatically be running `rustup target add wasm32-unknown-emscripten`. Does running that command manually fix the problem?

**Comment by flosse** [comment]
rustup does not work for NixOS but I installed the `wasm32-unknown-emscripten` manually.
Now it looks like this:
```
  Setup wasm running 'cargo build --target=wasm32-unknown-emscripten'
   Compiling meow v0.1.0 (file:///home/mk/dev/hello-wargo/meow)
error: linking with `emcc` failed: exit code: 1
  |
  = note: "emcc" "-s" "DISABLE_EXCEPTION_CATCHING=0" "-L" "/nix/store/dw362cm41l42hg8pp489nwxpclwd7rxz-combined-sysroots/lib/rustlib/wasm32-unknown-emscripten/lib" "/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.meow0.rust-cgu.o" "/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.meow1.rust-cgu.o" "-o" "/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.js" "-s" "EXPORTED_FUNCTIONS=[\"_main\",\"___rdl_grow_in_place\",\"___rdl_shrink_in_place\",\"___rdl_alloc_excess\",\"___rdl_alloc\",\"___rdl_oom\",\"___rdl_usable_size\",\"___rdl_dealloc\",\"___rdl_realloc_excess\",\"___rdl_realloc\",\"___rdl_alloc_zeroed\",\"_rust_eh_personality\"]" "/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.crate.allocator.rust-cgu.o" "-O0" "--memory-init-file" "0" "-g4" "-s" "DEFAULT_LIBRARY_FUNCS_TO_INCLUDE=[]" "-L" "/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps" "-L" "/home/mk/dev/hello-wargo/meow/target/debug/deps" "-L" "/nix/store/dw362cm41l42hg8pp489nwxpclwd7rxz-combined-sysroots/lib/rustlib/wasm32-unknown-emscripten/lib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libstd-8619326a58b69049.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc_system-7ab66d8b1dc07c88.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/librand-fb2e86da84f33f57.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libpanic_unwind-b0a5f6f855a7ba6e.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/liballoc-9e6751d60d680f40.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libstd_unicode-5335a01fae088e11.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libunwind-faa55fd0eab39cd3.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/liblibc-ecf22eb28c6217ef.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libcore-774d28f5c937ceca.rlib" "/nix/store/jzrsfdrvsm9bglnzn50qpaq6f6ycx4mh-rust-std-nightly-2017-10-22-wasm32-unknown-emscripten/lib/rustlib/wasm32-unknown-emscripten/lib/libcompiler_builtins-d93d2b7f1f97a75d.rlib" "-l" "c" "-s" "BINARYEN=1" "-s" "ERROR_ON_UNDEFINED_SYMBOLS=1"
  = note: Unknown option '--source-map'
          Traceback (most recent call last):
            File "/home/mk/.nix-profile/bin/emcc", line 13, in <module>
              emcc.run()
            File "/nix/store/y8iida32z1djriabvpnrjv6dggka3b2i-emscripten-1.37.16/share/emscripten/emcc.py", line 1785, in run
              wasm_text_target, misc_temp_files, optimizer)
            File "/nix/store/y8iida32z1djriabvpnrjv6dggka3b2i-emscripten-1.37.16/share/emscripten/emcc.py", line 2266, in do_binaryen
              subprocess.check_call(cmd)
            File "/nix/store/1snk2wkpv97an87pk1842fgskl1vqhkr-python-2.7.14/lib/python2.7/subprocess.py", line 186, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['/nix/store/fb92l1mz6n5c6gm0yyqx6sjrdvzam4xw-binaryen-33/bin/wasm-as', '/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.wast', '-o', '/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.wasm', '-g', '--source-map=/home/mk/dev/hello-wargo/meow/target/wasm32-unknown-emscripten/debug/deps/meow-5eb0351090adc8e2.wasm.map']' returned non-zero exit status 1

error: aborting due to previous error

error: Could not compile `meow`.
```

**Comment by flosse** [comment]
... I guess this is more NixOS related than wargo but it would be nice to use it anyway ;-)

**Comment by lord** [comment]
Yea, this looks like a pretty deep error with emcc that may be beyond our control. That said, if you manage to find a fix, I'd love to automate it and put it into wargo so other NixOS people don't have to solve it again!

I'm willing to be the [getos](https://www.npmjs.com/package/getos) would also love a PR that adds NixOS identification. That library failing to identify was what caused the original error.

**Comment by flosse** [comment]
I think we can close this for now.
Thanks for your help!

**Comment by sid-kap** [comment]
@flosse just curious, how did you install wasm32-unknown-emscripten on nixos?

**Comment by sid-kap** [comment]
@flosse I'm getting the same error as you on NixOS (Unknown option --source-map). Did you figure out why it was happening?

**Comment by sid-kap** [comment]
Update: the error clearly comes from a call to `wasm-as` (I couldn't figure out where), so I just got around it by using https://github.com/dflemstr/rust-native-wasm-loader instead of https://github.com/ianjsikes/rust-wasm-loader, since this loader doesn't use Emscripten. (It uses `wasm32-unknown-unknown` rather than `wasm32-unknown-emscripten`.)

(I wasn't using Wargo, by the way.)
